name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build collector
      run: go build -v -o symon-collector ./collector
      
    - name: Build aget
      run: go build -v -o symon-agent ./agent
      
    - name: Build client
      run: go build -v -o symon-client ./client
      
    - name: Test
      run: go test -v ./...
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* *.go* *.mod *.sum /*internal/*'
        
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'release.zip'
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        commit: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.GITHUB_TOKEN }}  
